before_script:
  - mkdir -p public/assets
  - go get -u github.com/gobuffalo/buffalo/buffalo
  - go mod download

stages:
  - test

.test-vars: &test-vars
  variables:
    GO_ENV: "test"

# Golang version choice helper
.use-golang-image: &use-golang-latest
  image: golang:latest

.use-golang-image: &use-golang-1-15
  image: golang:1.15

test:
  # Change to "<<: *use-golang-latest" to use the latest Go version
  <<: *use-golang-1-15
  <<: *test-vars
  stage: test
  script:
    - buffalo test
